spring:
  application:
    name: gateway
  profiles:
    active: dev
  mvc:
    static-path-pattern: /image/**
  resources:
   static-locations: file:/project4/server/resources/pic/
#    static-locations: file:/Users/ciggar/cskaoyan/csworkspace/qrcode/
  redisson:
      address: 127.0.0.1:6379
      timeout: 3000
      database: 0
      pool:
        max-active: 20
        max-idle: 10
        max-wait: 3000
        min-idle: 4

server:
  port: 8080
